//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupVolunteery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public groupVolunteery()
        {
            this.volunteerTimings = new HashSet<volunteerTiming>();
            this.volunteerToGroups = new HashSet<volunteerToGroup>();
        }
    
        public int id { get; set; }
        public string nameGroup { get; set; }
        public Nullable<int> sum_hour_in_night { get; set; }
        public Nullable<int> sum_hour_volunteering_for_week { get; set; }
        public Nullable<int> managerId { get; set; }
        public Nullable<System.TimeSpan> from_hour_in_night { get; set; }
        public Nullable<System.TimeSpan> to_hour_in_night { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteerTiming> volunteerTimings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteerToGroup> volunteerToGroups { get; set; }
    }
}
