//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteerSchedule
    {
        public int id { get; set; }
        public Nullable<int> weekDay { get; set; }
        public Nullable<System.TimeSpan> fromHour { get; set; }
        public Nullable<System.TimeSpan> toHour { get; set; }
        public Nullable<int> volunteerToGroupId { get; set; }
        public string comment { get; set; }
    
        public virtual volunteerToGroup volunteerToGroup { get; set; }
    }
}
